### PR TITLE
New pumpkin models / textures

### PR DESCRIPTION
**Pull request by kilbith**
(Note : the pumpkin face is punchable for lighting)

screenshot_3400804480

### CODE REVIEW

**Comment by rubenwardy** [comment]
I'm not too sure about this. They look more realistic, but is that really what we want?

**Comment by kilbith** [comment]
Why have created Nodebox Editor so ? "Let's make Minetest beautiful." ;)

**Comment by rubenwardy** [comment]
Lol. I personally like it, but I am worried that people won't because it isn't as voxel as the old one. Then again, this is a mod, not minetest_game.

**Comment by kilbith** [comment]
Indeed, it's not minetest_game.

Some items requires details to have a decent aspect. If every modder only did full cubic nodes, we would have a boring / ugly game. MT can do better than the classic voxel-games, and players appreciate that alot.

**Comment by PilzAdam** [comment]
I'm sorry, but I'd like to keep them cubes, since Minetest is a cube based game.
You could post your fork on the forums, though, so people can use it if they want.

**Comment by kilbith** [comment]
Nope, there are enough forks of this mod. Well then, it's a pity for us.

IMO, a full cubic pumpkin do not deserve to be called "pumpkin"...

**Comment by rubenwardy** [comment]
Try tenplu1's farming_plus redo.

**Pull request closed without merging**
